spring.application.name=hotel
server.port=8082


# ── Conexión a PostgreSQL ──────────────────────────────────────
spring.datasource.url=jdbc:postgresql://localhost:5432/hotel
spring.datasource.username=postgres
spring.datasource.password=Juana731026*
spring.datasource.driver-class-name=org.postgresql.Driver
 
# ── Pool de conexiones (HikariCP viene incluido) ────────────────
spring.datasource.hikari.maximum-pool-size=5
 
# ── Ver las queries en consola (solo en desarrollo) ─────────────
logging.level.org.springframework.jdbc.core=DEBUG
